# Local 환경에서 개발 시 사용될 profile 입니다.
spring:
  datasource:
    url: jdbc:mysql://localhost:${LOCAL_MYSQL_PORT}/aroom?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USERNAME}
    password: ${LOCAL_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

service:
  jwt:
    secret-key: kj23h523kj5h24o1209481230948fsdfkljut90dgd89f0s2kl3daisoudqiwouekjashdjkahjkaqwueyqouasioudklascxcvhjuopqfu9aduro3
    access-expiration: 36000000
    refresh-expiration: 864000000
